import 'package:csv/csv.dart';

import '../../transactions/domain/transaction.dart';

class ExportService {
  const ExportService();

  String transactionsCsv(List<FinanceTransaction> transactions) {
    final rows = [
      [
        'date',
        'type',
        'amount',
        'currency',
        'account',
        'category',
        'merchant',
        'note',
      ],
      for (final transaction in transactions)
        [
          transaction.date.toIso8601String(),
          transaction.type.name,
          transaction.amount.amount.toString(),
          transaction.amount.currency,
          transaction.accountId,
          transaction.categoryId ?? '',
          transaction.merchant ?? '',
          transaction.note ?? '',
        ],
    ];
    return csv.encode(rows);
  }

  String transactionsExcelCsv(List<FinanceTransaction> transactions) {
    return '\uFEFF${transactionsCsv(transactions)}';
  }

  String statementHtml({
    required String title,
    required List<FinanceTransaction> transactions,
  }) {
    final rows = transactions
        .map(
          (transaction) =>
              '<tr><td>${transaction.date.toIso8601String().split('T').first}</td>'
              '<td>${transaction.type.name}</td>'
              '<td>${transaction.merchant ?? ''}</td>'
              '<td>${transaction.amount.format()}</td></tr>',
        )
        .join();
    return '''
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>$title</title>
  <style>
    body { font-family: Arial, sans-serif; color: #0f172a; }
    h1 { color: #1d4ed8; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border-bottom: 1px solid #dce4f8; padding: 8px; text-align: left; }
  </style>
</head>
<body>
  <h1>$title</h1>
  <p>Generated by Aiko. Review before sharing sensitive financial data.</p>
  <table>
    <thead><tr><th>Date</th><th>Type</th><th>Merchant</th><th>Amount</th></tr></thead>
    <tbody>$rows</tbody>
  </table>
</body>
</html>
''';
  }
}
