project_id = "aiko-cloud"

[api]
enabled = true
schemas = ["public", "storage"]

[db]
major_version = 15

[studio]
enabled = true

[auth]
enabled = true
site_url = "io.aiko.app://auth"
additional_redirect_urls = ["io.aiko.app://auth/callback"]

[storage]
enabled = true
