// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20260523055312_up = [
  InsertTable('OfflineAccount'),
  InsertTable('OfflineBudget'),
  InsertTable('OfflineCategory'),
  InsertTable('OfflineGoal'),
  InsertTable('OfflineProfile'),
  InsertTable('OfflineTransaction'),
  InsertColumn('id', Column.varchar, onTable: 'OfflineAccount', unique: true),
  InsertColumn('user_id', Column.varchar, onTable: 'OfflineAccount'),
  InsertColumn('name', Column.varchar, onTable: 'OfflineAccount'),
  InsertColumn('type', Column.varchar, onTable: 'OfflineAccount'),
  InsertColumn('currency', Column.varchar, onTable: 'OfflineAccount'),
  InsertColumn('opening_balance', Column.varchar, onTable: 'OfflineAccount'),
  InsertColumn('current_balance', Column.varchar, onTable: 'OfflineAccount'),
  InsertColumn('institution', Column.varchar, onTable: 'OfflineAccount'),
  InsertColumn(
    'include_in_net_worth',
    Column.boolean,
    onTable: 'OfflineAccount',
  ),
  InsertColumn('is_active', Column.boolean, onTable: 'OfflineAccount'),
  InsertColumn('id', Column.varchar, onTable: 'OfflineBudget', unique: true),
  InsertColumn('user_id', Column.varchar, onTable: 'OfflineBudget'),
  InsertColumn('name', Column.varchar, onTable: 'OfflineBudget'),
  InsertColumn('category_id', Column.varchar, onTable: 'OfflineBudget'),
  InsertColumn('amount', Column.varchar, onTable: 'OfflineBudget'),
  InsertColumn('currency', Column.varchar, onTable: 'OfflineBudget'),
  InsertColumn('period_start', Column.datetime, onTable: 'OfflineBudget'),
  InsertColumn('period_end', Column.datetime, onTable: 'OfflineBudget'),
  InsertColumn('period', Column.varchar, onTable: 'OfflineBudget'),
  InsertColumn('alert_thresholds', Column.varchar, onTable: 'OfflineBudget'),
  InsertColumn('status', Column.varchar, onTable: 'OfflineBudget'),
  InsertColumn('id', Column.varchar, onTable: 'OfflineCategory', unique: true),
  InsertColumn('user_id', Column.varchar, onTable: 'OfflineCategory'),
  InsertColumn('name', Column.varchar, onTable: 'OfflineCategory'),
  InsertColumn('type', Column.varchar, onTable: 'OfflineCategory'),
  InsertColumn('category_group', Column.varchar, onTable: 'OfflineCategory'),
  InsertColumn('parent_id', Column.varchar, onTable: 'OfflineCategory'),
  InsertColumn('icon', Column.varchar, onTable: 'OfflineCategory'),
  InsertColumn('color', Column.varchar, onTable: 'OfflineCategory'),
  InsertColumn('budget_enabled', Column.boolean, onTable: 'OfflineCategory'),
  InsertColumn('is_active', Column.boolean, onTable: 'OfflineCategory'),
  InsertColumn('id', Column.varchar, onTable: 'OfflineGoal', unique: true),
  InsertColumn('user_id', Column.varchar, onTable: 'OfflineGoal'),
  InsertColumn('name', Column.varchar, onTable: 'OfflineGoal'),
  InsertColumn('purpose', Column.varchar, onTable: 'OfflineGoal'),
  InsertColumn('target_amount', Column.varchar, onTable: 'OfflineGoal'),
  InsertColumn('current_amount', Column.varchar, onTable: 'OfflineGoal'),
  InsertColumn('currency', Column.varchar, onTable: 'OfflineGoal'),
  InsertColumn('target_date', Column.datetime, onTable: 'OfflineGoal'),
  InsertColumn('linked_account_id', Column.varchar, onTable: 'OfflineGoal'),
  InsertColumn('priority', Column.integer, onTable: 'OfflineGoal'),
  InsertColumn('success_probability', Column.Double, onTable: 'OfflineGoal'),
  InsertColumn('status', Column.varchar, onTable: 'OfflineGoal'),
  InsertColumn('id', Column.varchar, onTable: 'OfflineProfile', unique: true),
  InsertColumn('display_name', Column.varchar, onTable: 'OfflineProfile'),
  InsertColumn('email', Column.varchar, onTable: 'OfflineProfile'),
  InsertColumn('base_currency', Column.varchar, onTable: 'OfflineProfile'),
  InsertColumn('country', Column.varchar, onTable: 'OfflineProfile'),
  InsertColumn('timezone', Column.varchar, onTable: 'OfflineProfile'),
  InsertColumn('preferred_theme', Column.varchar, onTable: 'OfflineProfile'),
  InsertColumn(
    'aiko_character_visibility',
    Column.varchar,
    onTable: 'OfflineProfile',
  ),
  InsertColumn(
    'aiko_personality_setting',
    Column.varchar,
    onTable: 'OfflineProfile',
  ),
  InsertColumn('ai_consent_enabled', Column.boolean, onTable: 'OfflineProfile'),
  InsertColumn('onboarding_status', Column.varchar, onTable: 'OfflineProfile'),
  InsertColumn('security_status', Column.varchar, onTable: 'OfflineProfile'),
  InsertColumn(
    'id',
    Column.varchar,
    onTable: 'OfflineTransaction',
    unique: true,
  ),
  InsertColumn('user_id', Column.varchar, onTable: 'OfflineTransaction'),
  InsertColumn('account_id', Column.varchar, onTable: 'OfflineTransaction'),
  InsertColumn('type', Column.varchar, onTable: 'OfflineTransaction'),
  InsertColumn('amount', Column.varchar, onTable: 'OfflineTransaction'),
  InsertColumn('currency', Column.varchar, onTable: 'OfflineTransaction'),
  InsertColumn('date', Column.datetime, onTable: 'OfflineTransaction'),
  InsertColumn('category_id', Column.varchar, onTable: 'OfflineTransaction'),
  InsertColumn('merchant', Column.varchar, onTable: 'OfflineTransaction'),
  InsertColumn('note', Column.varchar, onTable: 'OfflineTransaction'),
  InsertColumn('tags', Column.varchar, onTable: 'OfflineTransaction'),
  InsertColumn('status', Column.varchar, onTable: 'OfflineTransaction'),
  CreateIndex(columns: ['user_id'], onTable: 'OfflineAccount', unique: false),
  CreateIndex(columns: ['user_id'], onTable: 'OfflineBudget', unique: false),
  CreateIndex(columns: ['user_id'], onTable: 'OfflineCategory', unique: false),
  CreateIndex(columns: ['user_id'], onTable: 'OfflineGoal', unique: false),
  CreateIndex(
    columns: ['user_id'],
    onTable: 'OfflineTransaction',
    unique: false,
  ),
  CreateIndex(
    columns: ['account_id'],
    onTable: 'OfflineTransaction',
    unique: false,
  ),
];

const List<MigrationCommand> _migration_20260523055312_down = [
  DropTable('OfflineAccount'),
  DropTable('OfflineBudget'),
  DropTable('OfflineCategory'),
  DropTable('OfflineGoal'),
  DropTable('OfflineProfile'),
  DropTable('OfflineTransaction'),
  DropColumn('id', onTable: 'OfflineAccount'),
  DropColumn('user_id', onTable: 'OfflineAccount'),
  DropColumn('name', onTable: 'OfflineAccount'),
  DropColumn('type', onTable: 'OfflineAccount'),
  DropColumn('currency', onTable: 'OfflineAccount'),
  DropColumn('opening_balance', onTable: 'OfflineAccount'),
  DropColumn('current_balance', onTable: 'OfflineAccount'),
  DropColumn('institution', onTable: 'OfflineAccount'),
  DropColumn('include_in_net_worth', onTable: 'OfflineAccount'),
  DropColumn('is_active', onTable: 'OfflineAccount'),
  DropColumn('id', onTable: 'OfflineBudget'),
  DropColumn('user_id', onTable: 'OfflineBudget'),
  DropColumn('name', onTable: 'OfflineBudget'),
  DropColumn('category_id', onTable: 'OfflineBudget'),
  DropColumn('amount', onTable: 'OfflineBudget'),
  DropColumn('currency', onTable: 'OfflineBudget'),
  DropColumn('period_start', onTable: 'OfflineBudget'),
  DropColumn('period_end', onTable: 'OfflineBudget'),
  DropColumn('period', onTable: 'OfflineBudget'),
  DropColumn('alert_thresholds', onTable: 'OfflineBudget'),
  DropColumn('status', onTable: 'OfflineBudget'),
  DropColumn('id', onTable: 'OfflineCategory'),
  DropColumn('user_id', onTable: 'OfflineCategory'),
  DropColumn('name', onTable: 'OfflineCategory'),
  DropColumn('type', onTable: 'OfflineCategory'),
  DropColumn('category_group', onTable: 'OfflineCategory'),
  DropColumn('parent_id', onTable: 'OfflineCategory'),
  DropColumn('icon', onTable: 'OfflineCategory'),
  DropColumn('color', onTable: 'OfflineCategory'),
  DropColumn('budget_enabled', onTable: 'OfflineCategory'),
  DropColumn('is_active', onTable: 'OfflineCategory'),
  DropColumn('id', onTable: 'OfflineGoal'),
  DropColumn('user_id', onTable: 'OfflineGoal'),
  DropColumn('name', onTable: 'OfflineGoal'),
  DropColumn('purpose', onTable: 'OfflineGoal'),
  DropColumn('target_amount', onTable: 'OfflineGoal'),
  DropColumn('current_amount', onTable: 'OfflineGoal'),
  DropColumn('currency', onTable: 'OfflineGoal'),
  DropColumn('target_date', onTable: 'OfflineGoal'),
  DropColumn('linked_account_id', onTable: 'OfflineGoal'),
  DropColumn('priority', onTable: 'OfflineGoal'),
  DropColumn('success_probability', onTable: 'OfflineGoal'),
  DropColumn('status', onTable: 'OfflineGoal'),
  DropColumn('id', onTable: 'OfflineProfile'),
  DropColumn('display_name', onTable: 'OfflineProfile'),
  DropColumn('email', onTable: 'OfflineProfile'),
  DropColumn('base_currency', onTable: 'OfflineProfile'),
  DropColumn('country', onTable: 'OfflineProfile'),
  DropColumn('timezone', onTable: 'OfflineProfile'),
  DropColumn('preferred_theme', onTable: 'OfflineProfile'),
  DropColumn('aiko_character_visibility', onTable: 'OfflineProfile'),
  DropColumn('aiko_personality_setting', onTable: 'OfflineProfile'),
  DropColumn('ai_consent_enabled', onTable: 'OfflineProfile'),
  DropColumn('onboarding_status', onTable: 'OfflineProfile'),
  DropColumn('security_status', onTable: 'OfflineProfile'),
  DropColumn('id', onTable: 'OfflineTransaction'),
  DropColumn('user_id', onTable: 'OfflineTransaction'),
  DropColumn('account_id', onTable: 'OfflineTransaction'),
  DropColumn('type', onTable: 'OfflineTransaction'),
  DropColumn('amount', onTable: 'OfflineTransaction'),
  DropColumn('currency', onTable: 'OfflineTransaction'),
  DropColumn('date', onTable: 'OfflineTransaction'),
  DropColumn('category_id', onTable: 'OfflineTransaction'),
  DropColumn('merchant', onTable: 'OfflineTransaction'),
  DropColumn('note', onTable: 'OfflineTransaction'),
  DropColumn('tags', onTable: 'OfflineTransaction'),
  DropColumn('status', onTable: 'OfflineTransaction'),
  DropIndex('index_OfflineAccount_on_user_id'),
  DropIndex('index_OfflineBudget_on_user_id'),
  DropIndex('index_OfflineCategory_on_user_id'),
  DropIndex('index_OfflineGoal_on_user_id'),
  DropIndex('index_OfflineTransaction_on_user_id'),
  DropIndex('index_OfflineTransaction_on_account_id'),
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20260523055312',
  up: _migration_20260523055312_up,
  down: _migration_20260523055312_down,
)
class Migration20260523055312 extends Migration {
  const Migration20260523055312()
    : super(
        version: 20260523055312,
        up: _migration_20260523055312_up,
        down: _migration_20260523055312_down,
      );
}
